---
- name: config system
  uci:
    command: set
    key: system.@system[0].{{ item.key }}
    value: "{{ item.value }}"
  with_dict: "{{ system }}"
  notify:
    - uci commit
    - reload system

- name: set bogusnxdomain
  uci:
    command: add_list
    key: dhcp.@dnsmasq[0].bogusnxdomain
    value: "{{ item }}"
  with_items: "{{ bogusnxdomain }}"
  notify:
    - uci commit
    - restart dnsmasq
